name: Test_image_Pull
on:
  push:
    branches:
      - "*"
jobs:
 Test_image_pull:
    name: Test_image_pull
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/vineeth1992/publish_to_gcr:main
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        
    steps:

      - name: checkout repository
        uses: actions/checkout@v3

      - name: 'Setup Node'
        uses: actions/setup-node@v2
        with:
          node-version: '14'
